# Generated by Django 2.2.4 on 2019-09-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authordetail',
            name='info',
            field=models.TextField(default='哈哈哈'),
        ),
    ]
